site_name: aiovalorant

theme:
  name: "material"
  palette:
    - scheme: default
      accent: deep orange
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: deep orange
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_name: Shinobou/aiovalorant
repo_url: https://github.com/Shinobou/aiovalorant

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
- awesome-pages


nav:
  - Home: index.md
  - API Reference:
    - aiovalorant:
        - Client.md
        - DoesNotExist.md
        - MissingOrInvalidParameters.md
        - ValorantAPIException.md
        - agents: agents.md
        - buddies: buddies.md
        - bundles: bundles.md
        - ceremonies: ceremonies.md
        - competitive_tiers: competitive_tiers.md
        - content_tiers: content_tiers.md
        - contracts: contracts.md
        - currencies: currencies.md
        - events: events.md
        - gamemodes: gamemodes.md
        - gear: gear.md
        - level_borders: level_borders.md
        - maps: maps.md
        - player_cards: player_cards.md
        - seasons: seasons.md
        - sprays: sprays.md
        - themes: themes.md
        - traits: traits.md
        - version: version.md
        - weapons: weapons.md